# Generated by Django 5.1.4 on 2026-10-05 08:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_code', models.CharField(editable=False, max_length=8, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('funeral', 'Funeral or memorial'), ('church', 'Church event'), ('corporate', 'Corporate function'), ('graduation', 'Graduation'), ('other', 'Other')], default='other', max_length=20)),
                ('event_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.CharField(blank=True, help_text='Storage key', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('allow_uploads', models.BooleanField(default=True)),
                ('allow_downloads', models.BooleanField(default=False, verbose_name='Let guests download originals')),
                ('moderation_enabled', models.BooleanField(default=False)),
                ('max_upload_size_mb', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('max_photos_per_upload', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('view_pin_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('storage_used_bytes', models.PositiveBigIntegerField(default=0)),
                ('expiry_marked_at', models.DateTimeField(blank=True, null=True)),
                ('files_purged_at', models.DateTimeField(blank=True, null=True)),
                ('warned_thresholds', models.CharField(blank=True, help_text='Warning days already emailed, e.g. 7,1', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='events_even_owner_i_cd92aa_idx')],
            },
        ),
    ]
