# Generated by Django 5.1.4 on 2026-10-08 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_video_size_mb',
            field=models.PositiveIntegerField(default=500, help_text='Maximum size per video in MB.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_upload_size_mb',
            field=models.PositiveSmallIntegerField(default=15, help_text='Maximum size per photo in MB.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
