# Generated by Django 5.1.4 on 2026-10-05 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='uploading', max_length=12)),
                ('uploader_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_hash', models.CharField(max_length=64)),
                ('uploader_name', models.CharField(blank=True, max_length=60)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('batch_id', models.UUIDField(blank=True, null=True)),
                ('declared_content_type', models.CharField(max_length=30)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('original_bytes', models.PositiveBigIntegerField(default=0)),
                ('medium_bytes', models.PositiveBigIntegerField(default=0)),
                ('thumb_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.CharField(blank=True, max_length=200)),
                ('auto_hidden', models.BooleanField(default=False, help_text='Hidden automatically after too many reports')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate or offensive'), ('privacy', 'Privacy concern'), ('spam', 'Spam or unrelated'), ('other', 'Something else')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('reporter_hash', models.CharField(max_length=64)),
                ('dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='photos.photo')),
            ],
        ),
        migrations.CreateModel(
            name='UploadConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_hash', models.CharField(max_length=64)),
                ('ip_hash', models.CharField(max_length=64)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='events.event')),
            ],
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['event', 'status', 'created_at'], name='photos_phot_event_i_c36a22_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['event', 'content_hash'], name='photos_phot_event_i_29b3ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(condition=models.Q(('content_hash', ''), _negated=True), fields=('event', 'content_hash'), name='uniq_event_content_hash'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('photo', 'reporter_hash'), name='uniq_report_device'),
        ),
        migrations.AddConstraint(
            model_name='uploadconsent',
            constraint=models.UniqueConstraint(fields=('event', 'device_hash'), name='uniq_consent_device'),
        ),
    ]
