# Generated by Django 5.1.4 on 2026-10-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='photo',
            name='original_ext',
            field=models.CharField(blank=True, help_text='Extension of the stored original', max_length=8),
        ),
        migrations.AddField(
            model_name='photo',
            name='poster_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='upload_id',
            field=models.CharField(blank=True, help_text='S3 multipart upload id, if any', max_length=180),
        ),
        migrations.AlterField(
            model_name='photo',
            name='declared_content_type',
            field=models.CharField(default='image/jpeg', max_length=30),
        ),
    ]
