"""Swappable photo storage interface."""
from typing import IO, Protocol


class PhotoStorage(Protocol):
    def put(self, key: str, data: "bytes | IO", content_type: str) -> None: ...
    def get_stream(self, key: str) -> IO: ...
    def delete(self, key: str) -> None: ...
    def delete_prefix(self, prefix: str) -> None: ...
    def exists(self, key: str) -> bool: ...
    def size(self, key: str) -> int: ...
    def copy(self, src: str, dst: str) -> None: ...
    def url(self, key: str, expires: int = 3600, download_name: "str | None" = None) -> str: ...
    def presign_upload(self, key: str, content_type: str, max_bytes: int,
                       expires: int = 600) -> "dict | None": ...
    def create_multipart(self, key: str, content_type: str) -> "dict | None": ...
    def presign_part(self, key: str, upload_id: str, part_number: int,
                     expires: int = 600) -> "str | None": ...
    def complete_multipart(self, key: str, upload_id: str, parts: list) -> None: ...
    def abort_multipart(self, key: str, upload_id: str) -> None: ...